name: skillGenie

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  flutter_markdown: ^0.6.10
  # UI & Styling
  cupertino_icons: ^1.0.8
  auto_size_text: ^3.0.0
  google_fonts: ^4.0.4
  flutter_svg: ^1.0.1
  lottie: ^2.3.1
  animations: ^2.0.2
  smooth_page_indicator: ^1.1.0
  material_design_icons_flutter: ^7.0.7296
  flutter_spinkit: ^5.2.0

  font_awesome_flutter: ^10.4.0

  #speach to tesxt 
  


  animated_text_kit: ^4.2.2


  # Networking & API
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.3.1
  http: ^1.3.0
  convert: ^3.0.1
  http_parser: ^4.0.2
  socket_io_client: ^3.0.2
  url_launcher: ^6.2.5

  # State Management & Utilities
  provider: ^6.1.2
  go_router: ^14.8.0
  shared_preferences: ^2.5.1
  get_it: ^7.2.0
  uuid: ^4.4.2
  logger: ^1.0.0
  logging: ^1.3.0
  connectivity_plus: ^5.0.2
  intl: ^0.19.0
  date_format: ^2.0.7
  characters: ^1.2.0

  # AI & Cloud
  flutter_gemini: ^3.0.0
  google_generative_ai: ^0.4.6
  cloudinary_public: ^0.21.0
  cached_network_image: ^3.2.3

  # Image Processing & Media
  image_picker: ^1.1.2
  path_provider: ^2.1.2
  path: ^1.8.3
  flutter_image_compress: ^2.1.0
  mime: ^2.0.0
  sqflite: ^2.3.0
  flag: ^6.0.0
  syncfusion_flutter_pdf: ^28.2.6
  file_picker: ^9.0.0
  media_scanner: ^2.2.0
  gal: ^2.3.1
  permission_handler: ^11.4.0
  ffmpeg_kit_flutter_new: ^1.1.0
  flutter_pdfview: ^1.4.0
  ffmpeg_cli: ^0.3.0
  flutter_tts: ^4.2.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.2
  timeago: ^3.7.0
  video_player: ^2.9.5

  # UI Elements & Animations
  rflutter_alert: ^2.0.7
  page_transition: ^2.2.1
  flutter_code_editor: ^0.3.2
  flutter_dotenv: ^5.2.1
  flutter_animate: ^4.5.0

  flutter_secure_storage: ^8.0.0
  circular_countdown_timer: ^0.2.4
  json_annotation: ^4.8.1
  flutter_stripe: ^11.5.0
  js: ^0.6.7

  

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  generate: true  # Required for localizations
  uses-material-design: true
  assets:
    - assets/images/genie.png
    - assets/images/1.png
    - assets/images/0.png
    - assets/images/2.png
    - assets/images/gallow.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/5.png
    - assets/images/6.png
    - assets/images/loading.json
    - assets/images/avatar.json
    - assets/images/check.json
    - assets/images/motivation.json
    - assets/images/error.json
    - .env
    - assets/images/avatar1.png
    - assets/images/avatar2.png
    - assets/images/avatar3.png
    - assets/images/avatar4.png
    - assets/images/avatar5.png
    - assets/images/avatar6.png
    - assets/images/coin.jpeg
    - assets/coin_animation.json
    - res/hangman_words.txt
  fonts:
    - family: PatrickHand
      fonts:
        - asset: fonts/PatrickHand-Regular.ttf
    - family: FiraMono
      fonts:
        - asset: fonts/FiraMono-Bold.ttf
        - asset: fonts/FiraMono-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/genie.png"
  min_sdk_android: 21
